services:
  t122004:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: t122004
    volumes:
      - ./t122004:/usr/src/app
    ports:
      - "3001:3000"
    command: sh -c 'cd react-app && yarn start'
    tty: true
    stdin_open: true
  
  t122060:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: t122060
    volumes:
      - ./t122060:/usr/src/app
    ports:
      - "3002:3000"
    command: sh -c 'cd react-app && yarn start'
    tty: true
    stdin_open: true
  
  t122104:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: t122104
    volumes:
      - ./t122104:/usr/src/app
    ports:
      - "3003:3000"
    command: sh -c 'cd react-app && yarn start'
    tty: true
    stdin_open: true
#バックエンド
  t122104_back:
    build: 
      context: ./t122104_back
      dockerfile: Dockerfile
    container_name: t122104_back
    volumes:
      - ./t122104_back:/app
    
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=development
  
  t122152:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: t122152
    volumes:
      - ./t122152:/usr/src/app
    ports:
      - "3004:3000"
    command: sh -c 'cd react-app && yarn start'
    tty: true
    stdin_open: true
    
  t121103:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: t121103
    volumes:
      - ./t121103:/usr/src/app
    ports:
      - "3005:3000"
    command: sh -c 'cd react-app && yarn start'
    tty: true
    stdin_open: true
  
