version: '3'
 
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www/html/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c 'cd app && npm run winstart'